/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SimCardPoolService } from "../simCardPool.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SimCardPoolCreateInput } from "./SimCardPoolCreateInput";
import { SimCardPool } from "./SimCardPool";
import { SimCardPoolFindManyArgs } from "./SimCardPoolFindManyArgs";
import { SimCardPoolWhereUniqueInput } from "./SimCardPoolWhereUniqueInput";
import { SimCardPoolUpdateInput } from "./SimCardPoolUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SimCardPoolControllerBase {
  constructor(
    protected readonly service: SimCardPoolService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SimCardPool })
  @nestAccessControl.UseRoles({
    resource: "SimCardPool",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createSimCardPool(
    @common.Body() data: SimCardPoolCreateInput
  ): Promise<SimCardPool> {
    return await this.service.createSimCardPool({
      data: data,
      select: {
        createdAt: true,
        gammuExcluded: true,
        id: true,
        pool: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [SimCardPool] })
  @ApiNestedQuery(SimCardPoolFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "SimCardPool",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async simCardPools(@common.Req() request: Request): Promise<SimCardPool[]> {
    const args = plainToClass(SimCardPoolFindManyArgs, request.query);
    return this.service.simCardPools({
      ...args,
      select: {
        createdAt: true,
        gammuExcluded: true,
        id: true,
        pool: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SimCardPool })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SimCardPool",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async simCardPool(
    @common.Param() params: SimCardPoolWhereUniqueInput
  ): Promise<SimCardPool | null> {
    const result = await this.service.simCardPool({
      where: params,
      select: {
        createdAt: true,
        gammuExcluded: true,
        id: true,
        pool: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SimCardPool })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SimCardPool",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateSimCardPool(
    @common.Param() params: SimCardPoolWhereUniqueInput,
    @common.Body() data: SimCardPoolUpdateInput
  ): Promise<SimCardPool | null> {
    try {
      return await this.service.updateSimCardPool({
        where: params,
        data: data,
        select: {
          createdAt: true,
          gammuExcluded: true,
          id: true,
          pool: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SimCardPool })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SimCardPool",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSimCardPool(
    @common.Param() params: SimCardPoolWhereUniqueInput
  ): Promise<SimCardPool | null> {
    try {
      return await this.service.deleteSimCardPool({
        where: params,
        select: {
          createdAt: true,
          gammuExcluded: true,
          id: true,
          pool: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
